# Generated by Django 4.2.24 on 2025-09-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ต้ม', 'ต้ม'), ('ผัด', 'ผัด'), ('ทอด', 'ทอด'), ('ของหวาน', 'ของหวาน')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
