# Generated by Django 5.2.7 on 2025-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
